# ============================================================
# SmartPark :: User Service — Bootstrap
# All configuration is served by config-server.
# ============================================================

spring:
  application:
    name: user-service

  config:
    import: "optional:configserver:http://localhost:8888"
